server:
  servlet:
    session:
      timeout: 30m
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: lax

spring:
  application:
    name: board-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

observability:
  query:
    value-allowlist:
      - page
      - size
      - sort
